"""
pdf_generator.py — Complete BRSR-Audit-Ready PDF Generator

Covers:
- Cover page with overall score + section scores
- Section A (General Disclosures) — unchanged from v1
- Section B (NGRBC Policy Management)
- Principle 1 (Ethics)
- Principle 2 (Sustainable Products)
- Principle 3 (Employee Wellbeing)
- Principle 4+5 (Stakeholders & Human Rights)
- Principle 6 (Environment) — placeholder
- Principles 7-9 (Policy/Community/Customers) — placeholder
- Final recommendations
- Signature page

Call generate_brsr_pdf(merged_data, overall_score) from app.py
"""

from fpdf import FPDF
from datetime import datetime
from pathlib import Path

_PDF_BASE_DIR = Path(__file__).parent
ECOSETU_LOGO = str(_PDF_BASE_DIR / "assets" / "ecosetu_logo.png")
ECOSETU_ICON = str(_PDF_BASE_DIR / "assets" / "ecosetu_icon_128.png")


# ─────────────────────────────────────────────────────────────────────────────
# UTILITIES
# ─────────────────────────────────────────────────────────────────────────────
def clean(text):
    """Remove characters unsupported by Helvetica."""
    if text is None or text == "":
        return "-"
    return (str(text)
            .replace("–", "-")
            .replace("—", "-")
            .replace("\u2019", "'")
            .replace("\u2018", "'")
            .replace("\u201c", '"')
            .replace("\u201d", '"')
            .replace("₹", "Rs.")
            .replace("✅", "")
            .replace("❌", "")
            .replace("🔵", "")
            .replace("🟡", "")
            .replace("🟠", "")
            .replace("🔴", "")
            .replace("🟢", "")
            .replace("🎯", "")
            .replace("⚠️", "")
            .replace("🚨", "")
            .replace("🌍", "")
            .replace("🌿", "")
            .replace("💰", "")
            .replace("📌", "")
            .replace("🏢", "")
            .replace("🧮", "")
            .replace("🎉", "")
            .replace("📞", "")
            .replace("💧", "")
            .replace("⚡", "")
            .replace("🗑️", "")
            .replace("⚖️", "")
            .replace("🌱", "")
            .replace("📋", "")
            .replace("🤝", "")
            .replace("🏛️", "")
            .replace("🏘️", "")
            .replace("👥", "")
            .replace("📊", "")
            .replace("♻️", "")
            .replace("🔄", "")
            .replace("🔒", "")
            .replace("🏷️", "")
            .replace("🎨", ""))


def get_msme_class(turnover_lakhs):
    if turnover_lakhs == 0:
        return "-"
    if turnover_lakhs <= 500:
        return "Micro Enterprise"
    elif turnover_lakhs <= 5000:
        return "Small Enterprise"
    else:
        return "Medium Enterprise"


def safe_get(d, *keys, default="-"):
    """Safely traverse nested dicts. safe_get(data, 'p1', 'score', default=0)"""
    cur = d
    for k in keys:
        if isinstance(cur, dict):
            cur = cur.get(k)
        else:
            return default
    if cur is None or cur == "":
        return default
    return cur


def pct(n, d):
    try:
        if d and float(d) > 0:
            return round((float(n) / float(d)) * 100, 1)
        return 0
    except:
        return 0


# ─────────────────────────────────────────────────────────────────────────────
# MAIN PDF CLASS
# ─────────────────────────────────────────────────────────────────────────────
class BRSRReport(FPDF):

    def header(self):
        # Skip header on cover page (page 1)
        if self.page_no() == 1:
            return

        # Indigo bar (matches SaaS theme)
        self.set_fill_color(99, 102, 241)
        self.rect(0, 0, 210, 14, 'F')
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 10)
        self.set_y(4)
        self.cell(0, 6, "BUSINESS RESPONSIBILITY & SUSTAINABILITY REPORT", align="C")
        self.set_text_color(0, 0, 0)
        self.ln(12)

    def footer(self):
        # Skip footer on cover page
        if self.page_no() == 1:
            return
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7.5)
        self.set_text_color(148, 163, 184)
        self.cell(0, 4,
                  f"Generated by Ecosetu  |  Green compliance, bridged.  |  "
                  f"{datetime.now().strftime('%d %B %Y')}  |  Page {self.page_no()}",
                  align="C")
    # ── SECTION HEADING (full bar) ──────────────────────────────────────
    def section_heading(self, text):
        self.ln(4)
        self.set_fill_color(21, 128, 61)
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 10)
        self.cell(0, 8, f"  {clean(text)}", fill=True, ln=True)
        self.set_text_color(0, 0, 0)
        self.ln(2)

    # ── PRINCIPLE HEADING (smaller bar with icon) ───────────────────────
    def principle_heading(self, code, title):
        self.ln(3)
        self.set_fill_color(46, 125, 50)
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 11)
        self.cell(0, 9, f"  {clean(code)}: {clean(title)}", fill=True, ln=True)
        self.set_text_color(0, 0, 0)
        self.ln(2)

    # ── SUB HEADING ─────────────────────────────────────────────────────
    def sub_heading(self, text):
        self.ln(2)
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(21, 128, 61)
        self.cell(0, 6, clean(text), ln=True)
        self.set_text_color(0, 0, 0)

    # ── KEY-VALUE ROW ───────────────────────────────────────────────────
    def kv_row(self, label, value, shaded=False):
        if shaded:
            self.set_fill_color(245, 250, 245)
        else:
            self.set_fill_color(255, 255, 255)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(90, 90, 90)
        self.cell(70, 7, f"  {clean(label)}", border="B", fill=True)
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(0, 0, 0)
        v = clean(value) if value not in [None, "", 0, "0"] else "-"
        self.cell(0, 7, f"  {v}", border="B", fill=True, ln=True)

    # ── TABLE HEADER ────────────────────────────────────────────────────
    def table_header(self, cols, widths):
        self.set_fill_color(220, 240, 220)
        self.set_font("Helvetica", "B", 8)
        self.set_text_color(21, 80, 40)
        for col, w in zip(cols, widths):
            self.cell(w, 7, f" {clean(col)}", border=1, fill=True)
        self.ln()
        self.set_text_color(0, 0, 0)

    # ── TABLE ROW ───────────────────────────────────────────────────────
    def table_row(self, values, widths, shaded=False):
        if shaded:
            self.set_fill_color(250, 252, 250)
        else:
            self.set_fill_color(255, 255, 255)
        self.set_font("Helvetica", "", 8)
        for val, w in zip(values, widths):
            v = clean(val) if val not in [None, ""] else "-"
            self.cell(w, 6, f" {v}", border=1, fill=True)
        self.ln()

    # ── MULTI-LINE PARAGRAPH ────────────────────────────────────────────
    def paragraph(self, text, italic=False):
        self.set_font("Helvetica", "I" if italic else "", 9)
        self.set_text_color(70, 70, 70)
        self.multi_cell(0, 5, clean(text))
        self.set_text_color(0, 0, 0)
        self.ln(1)

    # ── ESG SCORE BOX ───────────────────────────────────────────────────
    def esg_score_box(self, score, label="ESG Readiness Score"):
        self.ln(4)
        self.set_fill_color(240, 250, 240)
        self.set_draw_color(21, 128, 61)
        self.set_line_width(0.5)
        self.rect(14, self.get_y(), 182, 28, 'FD')

        y = self.get_y() + 4
        self.set_xy(20, y)
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(21, 80, 40)
        self.cell(80, 6, clean(label))

        self.set_font("Helvetica", "B", 22)
        if score >= 70:
            self.set_text_color(21, 128, 61)
        elif score >= 40:
            self.set_text_color(200, 130, 0)
        else:
            self.set_text_color(180, 30, 30)
        self.cell(30, 10, f"{score}%")

        self.set_font("Helvetica", "B", 10)
        if score >= 70:
            rating = "HIGH - Strong ESG posture"
            self.set_text_color(21, 128, 61)
        elif score >= 40:
            rating = "MEDIUM - Room to improve"
            self.set_text_color(200, 130, 0)
        else:
            rating = "LOW - Action needed"
            self.set_text_color(180, 30, 30)
        self.cell(60, 10, rating)

        self.set_text_color(0, 0, 0)
        self.ln(18)

    # ── RECOMMENDATION BOX ──────────────────────────────────────────────
    def recommendation(self, text):
        self.set_fill_color(255, 251, 230)
        self.set_draw_color(200, 150, 0)
        self.set_line_width(0.3)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(100, 70, 0)
        self.multi_cell(0, 5, f"  Recommendation:  {clean(text)}", border=1, fill=True)
        self.set_text_color(0, 0, 0)
        self.set_draw_color(0, 0, 0)
        self.ln(1)

    # ── SMALL INFO LABEL ────────────────────────────────────────────────
    def info_label(self, text):
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(100, 100, 100)
        self.cell(0, 5, f"  {clean(text)}", ln=True)
        self.set_text_color(0, 0, 0)
        self.ln(1)


# ─────────────────────────────────────────────────────────────────────────────
# SECTION A RENDERER (unchanged from v1)
# ─────────────────────────────────────────────────────────────────────────────
def render_section_a(pdf, d):
    """Renders full Section A exactly as before."""
    pdf.section_heading("SECTION A - GENERAL DISCLOSURES")

    # ── I. Company Identity ──────────────────────────────────────────────
    pdf.sub_heading("I. Company Identity")
    pdf.kv_row("Company Name", d.get("company_name"), shaded=True)
    pdf.kv_row("CIN Number", d.get("cin") or "N/A (Proprietorship/Partnership)")
    pdf.kv_row("Year of Incorporation", d.get("year_started"), shaded=True)
    pdf.kv_row("Business Type", d.get("ownership"))
    pdf.kv_row("Financial Year", d.get("financial_year"), shaded=True)
    rb = d.get("reporting_boundary", "-")
    if isinstance(rb, str):
        rb = rb.split("-")[0].strip()
    pdf.kv_row("Reporting Boundary", rb)
    if str(d.get("listed", "")).startswith("Yes"):
        pdf.kv_row("Listed on Exchange",
                   ", ".join(d.get("stock_exchange", [])) or "-", shaded=True)
        pdf.kv_row("Paid-up Capital", d.get("paid_up_capital", "-"))

    # ── II. Contact Details ──────────────────────────────────────────────
    pdf.sub_heading("II. Contact Details")
    pdf.kv_row("Registered Office", d.get("address"), shaded=True)
    pdf.kv_row("Corporate Office", d.get("corporate_address") or d.get("address"))
    pdf.kv_row("Email", d.get("email"), shaded=True)
    pdf.kv_row("Phone", d.get("phone"))
    pdf.kv_row("Website", d.get("website") or "Not available", shaded=True)

    # ── III. BRSR Contact Person ────────────────────────────────────────
    pdf.sub_heading("III. BRSR Contact Person")
    pdf.kv_row("Name", d.get("brsr_person_name"), shaded=True)
    pdf.kv_row("Designation", d.get("brsr_person_designation"))
    pdf.kv_row("Email", d.get("brsr_person_email"), shaded=True)
    pdf.kv_row("Phone", d.get("brsr_person_phone"))

    # ── IV. Products/Services ───────────────────────────────────────────
    pdf.sub_heading("IV. Business Activities & Products")
    activities = d.get("activities", [])
    if activities:
        cols = ["S.No.", "Main Activity", "Business Activity", "% of Turnover"]
        widths = [15, 55, 75, 40]
        pdf.table_header(cols, widths)
        for i, act in enumerate(activities, 1):
            pdf.table_row(
                [str(i), act.get("main", "-"), act.get("sub", "-"),
                 f"{act.get('pct', 0)}%"],
                widths, shaded=(i % 2 == 0)
            )

    products = d.get("products", [])
    if products:
        pdf.ln(2)
        pdf.info_label("Products/Services (covering 90% of turnover)")
        cols = ["S.No.", "Product/Service", "NIC Code", "% of Turnover"]
        widths = [15, 90, 40, 40]
        pdf.table_header(cols, widths)
        for i, prod in enumerate(products, 1):
            pdf.table_row(
                [str(i), prod.get("name", "-"), prod.get("nic", "-"),
                 f"{prod.get('pct', 0)}%"],
                widths, shaded=(i % 2 == 0)
            )

    # ── V. Operations ──────────────────────────────────────────────────
    pdf.add_page()
    pdf.sub_heading("V. Operations")
    pdf.kv_row("Number of Plants / Offices in India",
               d.get("num_plants", 0), shaded=True)
    pdf.kv_row("States of Operation", d.get("num_states", "-"))
    pdf.kv_row("Number of Countries (Export)",
               d.get("num_countries", 0), shaded=True)

    # ── VI. Markets ───────────────────────────────────────────────────
    pdf.sub_heading("VI. Markets Served")
    pdf.kv_row("States in India", d.get("num_states", "-"), shaded=True)
    pdf.kv_row("Countries Exported To", d.get("num_countries", 0))
    pdf.kv_row("Export as % of Revenue", f"{d.get('export_pct', 0)}%", shaded=True)
    cust = d.get("customer_types", [])
    pdf.kv_row("Customer Types", ", ".join(cust) if cust else "-")

    # ── VII. Employees & Workers ─────────────────────────────────────────
    pdf.add_page()
    pdf.sub_heading("VII. Employees & Workers")
    cols = ["Category", "Total", "Male", "Female", "% Female"]
    widths = [62, 28, 28, 28, 39]
    pdf.table_header(cols, widths)

    def female_pct(f, t):
        return f"{pct(f, t)}%" if t else "0%"

    rows = [
        ("Permanent Employees",
         d.get("total_perm_emp", 0), d.get("perm_emp_male", 0),
         d.get("perm_emp_female", 0),
         female_pct(d.get("perm_emp_female", 0), d.get("total_perm_emp", 1))),
        ("Contract Employees",
         d.get("total_temp_emp", 0), d.get("temp_emp_male", 0),
         d.get("temp_emp_female", 0),
         female_pct(d.get("temp_emp_female", 0), d.get("total_temp_emp", 1))),
        ("Permanent Workers",
         d.get("total_perm_wkr", 0), d.get("perm_wkr_male", 0),
         d.get("perm_wkr_female", 0),
         female_pct(d.get("perm_wkr_female", 0), d.get("total_perm_wkr", 1))),
        ("Contract Workers",
         d.get("total_temp_wkr", 0), d.get("temp_wkr_male", 0),
         d.get("temp_wkr_female", 0),
         female_pct(d.get("temp_wkr_female", 0), d.get("total_temp_wkr", 1))),
        ("Differently Abled Employees",
         d.get("diff_emp", 0), "-", "-", "-"),
        ("Differently Abled Workers",
         d.get("diff_wkr", 0), "-", "-", "-"),
    ]
    for i, row in enumerate(rows):
        pdf.table_row(list(row), widths, shaded=(i % 2 == 0))
    pdf.ln(2)

    # ── VIII. Women in Leadership ────────────────────────────────────────
    if d.get("board_total", 0) > 0 or d.get("kmp_total", 0) > 0:
        pdf.sub_heading("VIII. Women in Leadership")
        cols = ["Role", "Total", "Women", "% Women"]
        widths = [80, 37, 37, 31]
        pdf.table_header(cols, widths)
        pdf.table_row(["Board of Directors",
                       str(d.get("board_total", 0)),
                       str(d.get("board_female", 0)),
                       female_pct(d.get("board_female", 0),
                                  d.get("board_total", 1))],
                      widths, shaded=True)
        pdf.table_row(["Key Management Personnel (KMP)",
                       str(d.get("kmp_total", 0)),
                       str(d.get("kmp_female", 0)),
                       female_pct(d.get("kmp_female", 0),
                                  d.get("kmp_total", 1))], widths)
        pdf.ln(2)
        if d.get("board_female", 0) == 0 and d.get("board_total", 0) > 0:
            pdf.recommendation(
                "No women on the Board of Directors. Adding at least one woman "
                "director improves ESG credibility and is increasingly expected "
                "by banks, large buyers, and government schemes."
            )

    # ── IX. Staff Turnover ───────────────────────────────────────────────
    pdf.sub_heading("IX. Staff Turnover Rate (3-Year Trend)")
    cols = ["Category", "FY 2024-25", "FY 2023-24", "FY 2022-23"]
    widths = [80, 37, 37, 31]
    pdf.table_header(cols, widths)
    pdf.table_row(["Permanent Employees",
                   f"{d.get('turnover_fy1', 0)}%",
                   f"{d.get('turnover_fy2', 0)}%",
                   f"{d.get('turnover_fy3', 0)}%"], widths, shaded=True)
    pdf.ln(2)

    # ── X. CSR ───────────────────────────────────────────────────────────
    pdf.sub_heading("X. CSR (Section 135, Companies Act 2013)")
    csr = str(d.get("csr_applicable", "Not Applicable"))
    if "Not Applicable" in csr:
        pdf.kv_row("CSR Applicability", "Not Applicable - below threshold")
    else:
        pdf.kv_row("CSR Applicability", "Applicable", shaded=True)
        pdf.kv_row("Annual Turnover", d.get("csr_turnover", "-"))
        pdf.kv_row("Net Worth", d.get("csr_networth", "-"), shaded=True)
    pdf.ln(2)

    # ── XI. Grievances ───────────────────────────────────────────────────
    pdf.sub_heading("XI. Complaints & Grievance Mechanism")
    has_g = d.get("has_grievance", False)
    pdf.kv_row("Grievance Mechanism in Place",
               "Yes" if has_g else "No - Not yet established")
    if d.get("grievance_url"):
        pdf.kv_row("Grievance Policy URL", d.get("grievance_url"), shaded=True)

    if not has_g:
        pdf.recommendation(
            "Establish a simple grievance mechanism - even a dedicated email ID or "
            "complaint register. This is a quick win that directly improves your "
            "BRSR score."
        )

    # ── XII. ESG Issues ─────────────────────────────────────────────────
    pdf.add_page()
    pdf.sub_heading("XII. Material ESG Risks & Opportunities")
    issues = [iss for iss in d.get("issues", []) if iss.get("topic")]
    if issues:
        cols = ["Issue", "Type", "Why It Matters", "How We Manage It"]
        widths = [38, 18, 65, 64]
        pdf.table_header(cols, widths)
        for i, iss in enumerate(issues):
            pdf.set_font("Helvetica", "", 7.5)
            if i % 2 == 0:
                pdf.set_fill_color(250, 252, 250)
            else:
                pdf.set_fill_color(255, 255, 255)
            pdf.cell(38, 6, f" {clean(iss.get('topic', '-'))[:22]}", border=1, fill=True)
            t = iss.get("type", "-")
            if t == "Risk":
                pdf.set_text_color(160, 30, 30)
            else:
                pdf.set_text_color(21, 100, 50)
            pdf.cell(18, 6, f" {clean(t)}", border=1, fill=True)
            pdf.set_text_color(0, 0, 0)
            pdf.cell(65, 6, f" {clean(iss.get('rationale', '-'))[:60]}",
                     border=1, fill=True)
            pdf.cell(64, 6, f" {clean(iss.get('mitigation', '-'))[:60]}",
                     border=1, fill=True)
            pdf.ln()
    else:
        pdf.info_label("No material issues reported.")


# ─────────────────────────────────────────────────────────────────────────────
# SECTION B RENDERER — NGRBC POLICY MANAGEMENT
# ─────────────────────────────────────────────────────────────────────────────
PRINCIPLE_NAMES = {
    "P1": "Ethics & Integrity",
    "P2": "Sustainable Products",
    "P3": "Employee Wellbeing",
    "P4": "Stakeholder Engagement",
    "P5": "Human Rights",
    "P6": "Environment",
    "P7": "Policy Advocacy",
    "P8": "Inclusive Growth",
    "P9": "Customer Responsibility",
}


def render_section_b(pdf, data):
    """Section B — Management & Process Disclosures (NGRBC)"""
    b = data.get("section_b", {})
    if not b:
        return

    pdf.add_page()
    pdf.section_heading("SECTION B - MANAGEMENT & PROCESS DISCLOSURES")
    pdf.paragraph(
        "This section demonstrates the structures, policies, and processes "
        "put in place toward adopting the 9 NGRBC Principles."
    )

    # ── Policy Management Matrix ──────────────────────────────────────
    pdf.sub_heading("1. Policy & Management Processes (Per Principle)")

    cols = ["Principle", "Policy?", "Approved?", "Translated to Procedures?", "Extends to Suppliers?"]
    widths = [48, 25, 30, 45, 34]
    pdf.table_header(cols, widths)

    for code, name in PRINCIPLE_NAMES.items():
        row = [
            f"{code} - {name[:22]}",
            b.get(f"{code}_policy", "-"),
            b.get(f"{code}_approved", "-"),
            b.get(f"{code}_translated", "-"),
            b.get(f"{code}_value_chain", "-"),
        ]
        shaded = (list(PRINCIPLE_NAMES).index(code) % 2 == 0)
        pdf.table_row(row, widths, shaded=shaded)

    pdf.ln(3)

    # ── Certifications Summary ────────────────────────────────────────
    pdf.sub_heading("2. Certifications & Standards Adopted")
    cert_found = False
    for code, name in PRINCIPLE_NAMES.items():
        certs = b.get(f"{code}_certs", [])
        if certs and certs != ["None"] and len(certs) > 0:
            cert_text = ", ".join([c for c in certs if c != "None"])
            if cert_text:
                pdf.kv_row(f"{code} - {name}", cert_text,
                           shaded=(list(PRINCIPLE_NAMES).index(code) % 2 == 0))
                cert_found = True
    if not cert_found:
        pdf.info_label("No certifications adopted yet.")

    pdf.ln(2)

    # ── Commitments & Goals ───────────────────────────────────────────
    pdf.sub_heading("3. Commitments, Goals & Targets")
    commitment_found = False
    for code, name in PRINCIPLE_NAMES.items():
        commit = b.get(f"{code}_commitment", "")
        if commit and str(commit).strip():
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(21, 80, 40)
            pdf.cell(0, 5, f"  {code} - {name}", ln=True)
            pdf.set_text_color(0, 0, 0)
            pdf.paragraph(str(commit))
            commitment_found = True
    if not commitment_found:
        pdf.info_label("No specific commitments documented yet.")

    # ── Governance ────────────────────────────────────────────────────
    pdf.add_page()
    pdf.sub_heading("4. Governance, Leadership & Oversight")
    pdf.kv_row("Responsible Person",
               b.get("gov_person_name", "-"), shaded=True)
    pdf.kv_row("Designation", b.get("gov_person_designation", "-"))
    pdf.kv_row("Sustainability Committee",
               b.get("gov_committee", "-"), shaded=True)
    pdf.kv_row("Review Frequency", b.get("gov_review_freq", "-"))
    pdf.kv_row("External Assessment",
               b.get("gov_external_assess", "-"), shaded=True)

    statement = b.get("gov_director_statement", "")
    if statement and str(statement).strip():
        pdf.ln(2)
        pdf.sub_heading("Director's Statement on ESG")
        pdf.paragraph(str(statement))


# ─────────────────────────────────────────────────────────────────────────────
# PRINCIPLE 1 — ETHICS & INTEGRITY
# ─────────────────────────────────────────────────────────────────────────────
def render_p1(pdf, data):
    p1 = data.get("p1", {}) or data.get("c_p1", {})
    if not p1:
        return

    pdf.add_page()
    pdf.principle_heading("PRINCIPLE 1", "Ethics, Transparency & Accountability")

    # Training
    pdf.sub_heading("1. Training & Awareness Programmes")
    pdf.kv_row("Training Conducted?",
               "Yes" if p1.get("training_conducted") == "Yes" else "No",
               shaded=True)
    pdf.kv_row("Number of Programmes", p1.get("training_count", 0))
    pdf.kv_row("Topics Covered", p1.get("training_topics", "-"), shaded=True)

    cols = ["Category", "Trained", "Total", "% Coverage"]
    widths = [60, 35, 35, 52]
    pdf.table_header(cols, widths)

    categories = [
        ("Board of Directors", "board_trained", "board_total_train"),
        ("Key Management Personnel (KMP)", "kmp_trained", "kmp_total_train"),
        ("Other Employees", "emp_trained", "emp_total_train"),
        ("Workers", "wkr_trained", "wkr_total_train"),
    ]
    for i, (label, trained_k, total_k) in enumerate(categories):
        t = p1.get(trained_k, 0)
        total = p1.get(total_k, 0)
        p = pct(t, total)
        pdf.table_row([label, str(t), str(total), f"{p}%"],
                      widths, shaded=(i % 2 == 0))
    pdf.ln(2)

    # Fines & Penalties
    pdf.sub_heading("2. Fines, Penalties & Regulatory Actions")
    had_fines = p1.get("had_fines", "No")
    pdf.kv_row("Any Fines/Penalties in FY?", had_fines, shaded=True)
    if had_fines == "Yes":
        pdf.kv_row("Total Fine Amount (Rs.)", p1.get("fine_amount", 0))
        pdf.kv_row("Brief of Cases", p1.get("fine_brief", "-"), shaded=True)
        pdf.kv_row("Corrective Action Taken",
                   p1.get("fine_corrective", "-"))
    pdf.ln(2)

    # Anti-Bribery
    pdf.sub_heading("3. Anti-Bribery / Anti-Corruption Policy")
    pdf.kv_row("Policy in place?",
               p1.get("anti_bribery_policy", "-"), shaded=True)
    pdf.kv_row("Policy Coverage",
               p1.get("anti_bribery_coverage", "-"))

    bribe_cases = p1.get("bribery_cases", 0)
    pdf.kv_row("Bribery Cases in FY", bribe_cases, shaded=True)
    if bribe_cases > 0:
        pdf.kv_row("Action Taken",
                   p1.get("bribery_action", "-"))
    pdf.ln(2)

    # Disciplinary / Complaints
    pdf.sub_heading("4. Disciplinary Actions & Complaints")
    pdf.kv_row("Complaints Received on Conflict of Interest",
               p1.get("conflict_complaints", 0), shaded=True)
    pdf.kv_row("Disciplinary Actions Taken on Directors/KMPs",
               p1.get("disciplinary_actions", 0))

    # Score
    score = p1.get("score", 0)
    if score:
        pdf.ln(3)
        pdf.sub_heading("Principle 1 Score")
        pdf.kv_row("Ethics Score", f"{score}/100", shaded=True)


# ─────────────────────────────────────────────────────────────────────────────
# PRINCIPLE 2 — SUSTAINABLE PRODUCTS
# ─────────────────────────────────────────────────────────────────────────────
def render_p2(pdf, data):
    p2 = data.get("p2", {}) or data.get("c_p2", {})
    if not p2:
        return

    pdf.add_page()
    pdf.principle_heading("PRINCIPLE 2", "Sustainable & Safe Products/Services")

    # R&D + Capex
    pdf.sub_heading("1. R&D and Capex on Sustainability")
    cols = ["Investment Type", "Current FY (%)", "Previous FY (%)", "Improvements"]
    widths = [40, 35, 35, 72]
    pdf.table_header(cols, widths)
    pdf.table_row(
        ["R&D",
         f"{p2.get('rd_pct_cur', 0)}%",
         f"{p2.get('rd_pct_prev', 0)}%",
         (p2.get("rd_improvements", "-") or "-")[:45]],
        widths, shaded=True
    )
    pdf.table_row(
        ["Capex",
         f"{p2.get('capex_pct_cur', 0)}%",
         f"{p2.get('capex_pct_prev', 0)}%",
         (p2.get("capex_improvements", "-") or "-")[:45]],
        widths
    )
    pdf.ln(2)

    # Sustainable Sourcing
    pdf.sub_heading("2. Sustainable Sourcing")
    pdf.kv_row("Sourcing Procedures in Place?",
               p2.get("sustainable_sourcing", "-"), shaded=True)
    if p2.get("sustainable_sourcing") == "Yes":
        pdf.kv_row("% of Inputs Sourced Sustainably",
                   f"{p2.get('sustainable_pct', 0)}%")
        if p2.get("sourcing_methods"):
            pdf.kv_row("Sourcing Methods",
                       ", ".join(p2.get("sourcing_methods", [])),
                       shaded=True)
    pdf.ln(2)

    # End-of-Life
    pdf.sub_heading("3. End-of-Life Management (Reuse / Recycle / Dispose)")
    cols = ["Waste Type", "Reused (MT)", "Recycled (MT)",
            "Disposed (MT)", "Total", "Recovery %"]
    widths = [36, 25, 26, 26, 22, 47]
    pdf.table_header(cols, widths)
    waste_types = [
        ("plastic", "Plastic"),
        ("ewaste", "E-waste"),
        ("hazardous", "Hazardous"),
        ("other", "Other"),
    ]
    for i, (key, label) in enumerate(waste_types):
        reuse = p2.get(f"{key}_reused_cur", 0) or 0
        recycle = p2.get(f"{key}_recycled_cur", 0) or 0
        dispose = p2.get(f"{key}_disposed_cur", 0) or 0
        total = reuse + recycle + dispose
        recovery = pct(reuse + recycle, total) if total > 0 else 0
        pdf.table_row(
            [label, f"{reuse}", f"{recycle}", f"{dispose}",
             f"{round(total, 2)}", f"{recovery}%"],
            widths, shaded=(i % 2 == 0)
        )
    pdf.ln(2)

    # EPR
    pdf.sub_heading("4. Extended Producer Responsibility (EPR)")
    pdf.kv_row("EPR Applicable to Business?",
               p2.get("epr_applicable", "-"), shaded=True)
    if p2.get("epr_applicable") == "Yes":
        pdf.kv_row("Waste Collection Plan Aligned with PCB EPR?",
                   p2.get("epr_pcb_aligned", "-"))
        if p2.get("epr_steps"):
            pdf.kv_row("Steps Taken to Align",
                       p2.get("epr_steps", "-"), shaded=True)

    # Leadership: LCA
    if p2.get("lca_done") == "Yes":
        pdf.ln(2)
        pdf.sub_heading("Leadership: Life Cycle Assessment (LCA)")
        pdf.kv_row("LCA Conducted?", "Yes", shaded=True)
        pdf.kv_row("Product/Service", p2.get("lca_product", "-"))
        pdf.kv_row("% of Turnover", f"{p2.get('lca_turnover_pct', 0)}%",
                   shaded=True)
        pdf.kv_row("External Agency?", p2.get("lca_external", "-"))

    # Score
    score = p2.get("score", 0)
    if score:
        pdf.ln(3)
        pdf.sub_heading("Principle 2 Score")
        pdf.kv_row("Sustainable Products Score",
                   f"{score}/100", shaded=True)


# ─────────────────────────────────────────────────────────────────────────────
# PRINCIPLE 3 — EMPLOYEE WELLBEING
# ─────────────────────────────────────────────────────────────────────────────
def render_p3(pdf, data):
    p3 = data.get("p3", {}) or data.get("c_p3", {})
    if not p3:
        return

    pdf.add_page()
    pdf.principle_heading("PRINCIPLE 3", "Employee & Worker Wellbeing")

    # Benefits coverage
    pdf.sub_heading("1. Employee Benefits Coverage")
    cols = ["Benefit Type", "Employees Covered", "Workers Covered", "% Total"]
    widths = [55, 40, 40, 47]
    pdf.table_header(cols, widths)

    benefits = [
        ("Health Insurance", "health_ins_emp", "health_ins_wkr"),
        ("Accident Insurance", "accident_ins_emp", "accident_ins_wkr"),
        ("Maternity Benefits", "maternity_emp", "maternity_wkr"),
        ("Paternity Benefits", "paternity_emp", "paternity_wkr"),
        ("Day-care Facilities", "daycare_emp", "daycare_wkr"),
    ]
    for i, (label, ek, wk) in enumerate(benefits):
        emp = p3.get(ek, 0) or 0
        wkr = p3.get(wk, 0) or 0
        total_staff = (data.get("total_perm_emp", 0) +
                       data.get("total_perm_wkr", 0))
        p = pct(emp + wkr, total_staff) if total_staff > 0 else 0
        pdf.table_row([label, str(emp), str(wkr), f"{p}%"],
                      widths, shaded=(i % 2 == 0))
    pdf.ln(2)

    # Safety
    pdf.sub_heading("2. Occupational Health & Safety")
    pdf.kv_row("Safety Management System in Place?",
               p3.get("safety_system", "-"), shaded=True)
    pdf.kv_row("Safety Training Conducted?",
               p3.get("safety_training", "-"))
    pdf.kv_row("Lost Time Injuries (LTI)",
               p3.get("lti_count", 0), shaded=True)
    pdf.kv_row("Fatalities in FY", p3.get("fatalities", 0))
    pdf.kv_row("Workplace Accidents (Reportable)",
               p3.get("accidents", 0), shaded=True)
    pdf.ln(2)

    # Grievance
    pdf.sub_heading("3. Grievance Redressal")
    pdf.kv_row("Grievance Mechanism for Employees?",
               p3.get("grievance_mechanism", "-"), shaded=True)
    pdf.kv_row("Complaints Received in FY",
               p3.get("grievance_received", 0))
    pdf.kv_row("Complaints Resolved",
               p3.get("grievance_resolved", 0), shaded=True)

    # Retirement Benefits
    pdf.ln(2)
    pdf.sub_heading("4. Retirement & Statutory Benefits")
    pdf.kv_row("PF Coverage %",
               f"{p3.get('pf_coverage_pct', 0)}%", shaded=True)
    pdf.kv_row("ESI Coverage %",
               f"{p3.get('esi_coverage_pct', 0)}%")
    pdf.kv_row("Gratuity Provision",
               p3.get("gratuity_provision", "-"), shaded=True)

    # Score
    score = p3.get("score", 0)
    if score:
        pdf.ln(3)
        pdf.sub_heading("Principle 3 Score")
        pdf.kv_row("Employee Wellbeing Score",
                   f"{score}/100", shaded=True)


# ─────────────────────────────────────────────────────────────────────────────
# PRINCIPLES 4 + 5 — STAKEHOLDERS & HUMAN RIGHTS
# ─────────────────────────────────────────────────────────────────────────────
def render_p45(pdf, data):
    p45 = data.get("p4_5", {}) or data.get("c_p45", {})
    if not p45:
        return

    pdf.add_page()
    pdf.principle_heading("PRINCIPLE 4", "Stakeholder Engagement")

    # P4 — Stakeholder identification
    pdf.sub_heading("1. Stakeholders Identified")
    stakeholders = p45.get("stakeholders", [])
    if stakeholders:
        pdf.kv_row("Key Stakeholder Groups",
                   ", ".join(stakeholders), shaded=True)
    else:
        pdf.info_label("No stakeholders documented.")

    pdf.kv_row("Formal Stakeholder Engagement Process?",
               p45.get("engagement_process", "-"))
    pdf.kv_row("Engagement Frequency",
               p45.get("engagement_frequency", "-"), shaded=True)

    # Channels
    channels = p45.get("engagement_channels", [])
    if channels:
        pdf.kv_row("Engagement Channels",
                   ", ".join(channels))

    # P4 Leadership — vulnerable groups
    pdf.ln(2)
    pdf.sub_heading("2. Vulnerable / Marginalized Stakeholders")
    pdf.kv_row("Special Engagement for Vulnerable Groups?",
               p45.get("vulnerable_engagement", "-"), shaded=True)
    if p45.get("vulnerable_details"):
        pdf.kv_row("How Engaged",
                   p45.get("vulnerable_details", "-"))

    # P5 — Human Rights
    pdf.add_page()
    pdf.principle_heading("PRINCIPLE 5", "Human Rights")

    pdf.sub_heading("1. Human Rights Training")
    pdf.kv_row("Training on Human Rights Conducted?",
               p45.get("hr_training", "-"), shaded=True)
    pdf.kv_row("% Employees Covered",
               f"{p45.get('hr_training_pct', 0)}%")
    pdf.kv_row("% Workers Covered",
               f"{p45.get('hr_training_wkr_pct', 0)}%", shaded=True)

    # Minimum Wage
    pdf.ln(2)
    pdf.sub_heading("2. Minimum Wage & Equal Pay")
    pdf.kv_row("All Paid Minimum Wage or Above?",
               p45.get("min_wage_all", "-"), shaded=True)
    pdf.kv_row("Male-Female Median Remuneration Ratio",
               p45.get("gender_pay_ratio", "-"))
    pdf.kv_row("Equal Pay for Equal Work Policy?",
               p45.get("equal_pay_policy", "-"), shaded=True)

    # Complaints
    pdf.ln(2)
    pdf.sub_heading("3. Human Rights Complaints in FY")
    cols = ["Category", "Received", "Resolved", "Pending"]
    widths = [80, 35, 35, 32]
    pdf.table_header(cols, widths)
    hr_categories = [
        ("Sexual Harassment", "sh_received", "sh_resolved", "sh_pending"),
        ("Discrimination", "disc_received", "disc_resolved", "disc_pending"),
        ("Child Labour", "child_received", "child_resolved", "child_pending"),
        ("Forced Labour", "forced_received", "forced_resolved",
         "forced_pending"),
        ("Wages Issues", "wage_received", "wage_resolved", "wage_pending"),
    ]
    for i, (label, rk, ok, pk) in enumerate(hr_categories):
        pdf.table_row([label,
                       str(p45.get(rk, 0) or 0),
                       str(p45.get(ok, 0) or 0),
                       str(p45.get(pk, 0) or 0)],
                      widths, shaded=(i % 2 == 0))
    pdf.ln(2)

    # POSH
    pdf.sub_heading("4. POSH (Prevention of Sexual Harassment)")
    pdf.kv_row("POSH Committee Formed?",
               p45.get("posh_committee", "-"), shaded=True)
    pdf.kv_row("POSH Policy Displayed?",
               p45.get("posh_display", "-"))

    # Score
    score = p45.get("score", 0)
    if score:
        pdf.ln(3)
        pdf.sub_heading("Principle 4+5 Score")
        pdf.kv_row("Stakeholder & Human Rights Score",
                   f"{score}/100", shaded=True)


# ─────────────────────────────────────────────────────────────────────────────
# PRINCIPLE 6 — ENVIRONMENT (Full BRSR format)
# ─────────────────────────────────────────────────────────────────────────────
def render_p6(pdf, data):
    p6 = data.get("p6", {})
    if not p6:
        return

    pdf.add_page()
    pdf.principle_heading("PRINCIPLE 6", "Environment")

    # ── Q1: Energy Consumption (Essential Indicator 1) ────────────────────
    pdf.sub_heading("1. Energy Consumption & Intensity (Essential Q1)")
    cols = ["Parameter", "Current FY", "Previous FY", "Unit"]
    widths = [75, 40, 40, 27]
    pdf.table_header(cols, widths)

    elec_cur = p6.get("electricity_kwh_yr", 0) or 0
    elec_prev = p6.get("electricity_kwh_prev", 0) or 0
    diesel_cur = p6.get("diesel_litres_yr", 0) or 0
    diesel_prev = p6.get("diesel_litres_prev", 0) or 0
    other_cur = p6.get("other_energy_kwh", 0) or 0
    total_gj = p6.get("total_energy_gj", 0) or 0
    turnover_rs = p6.get("turnover_rs", 0) or 0
    e_intensity = p6.get("energy_intensity", 0) or 0

    rows = [
        ("Total Electricity Consumption",
         f"{elec_cur:,.0f}", f"{elec_prev:,.0f}", "kWh"),
        ("Total Fuel Consumption (Diesel)",
         f"{diesel_cur:,}", f"{diesel_prev:,}", "Litres"),
        ("Energy from Other Sources (Solar/Biogas)",
         f"{other_cur:,.0f}", "-", "kWh"),
        ("Total Energy Consumption",
         f"{total_gj:.3f}", "-", "GJ"),
        ("Energy Intensity (per Rs. turnover)",
         f"{e_intensity:.8f}" if e_intensity else "-", "-", "GJ/Rs."),
    ]
    for i, row in enumerate(rows):
        pdf.table_row(list(row), widths, shaded=(i % 2 == 0))
    pdf.ln(2)

    # PAT Scheme
    pdf.sub_heading("2. PAT Scheme Designated Consumer (Essential Q2)")
    pdf.kv_row("PAT Scheme Applicable?",
               p6.get("pat_applicable", "No - not applicable (most MSMEs)"),
               shaded=True)

    # ── Q3: Water (Essential Indicator 3) ─────────────────────────────────
    pdf.add_page()
    pdf.sub_heading("3. Water Withdrawal & Consumption (Essential Q3)")
    cols = ["Source", "Current FY (kL)", "Previous FY (kL)"]
    widths = [100, 42, 40]
    pdf.table_header(cols, widths)

    water_full = p6.get("water_full", {})
    water_sources = [
        ("Surface Water (river, canal, lake)", "surface"),
        ("Groundwater (borewell, tubewell)", "ground"),
        ("Third Party (tanker, municipal)", "third"),
        ("Seawater / Desalinated", "sea"),
        ("Other sources", "other"),
    ]
    total_withdraw_cur = 0
    total_withdraw_prev = 0
    for i, (label, key) in enumerate(water_sources):
        cur = water_full.get(f"{key}_cur", 0) or 0
        prev = water_full.get(f"{key}_prev", 0) or 0
        total_withdraw_cur += cur
        total_withdraw_prev += prev
        pdf.table_row([label, f"{cur:.1f}", f"{prev:.1f}"],
                      widths, shaded=(i % 2 == 0))

    # Use water_kl_yr as fallback for total if full breakdown missing
    water_yr = p6.get("water_kl_yr", 0) or 0
    if total_withdraw_cur == 0 and water_yr > 0:
        total_withdraw_cur = water_yr

    pdf.set_font("Helvetica", "B", 8)
    pdf.set_fill_color(230, 245, 230)
    pdf.cell(100, 6, " Total Water Withdrawal", border=1, fill=True)
    pdf.cell(42, 6, f" {total_withdraw_cur:.1f}", border=1, fill=True)
    pdf.cell(40, 6, f" {total_withdraw_prev:.1f}", border=1, fill=True)
    pdf.ln()
    pdf.set_font("Helvetica", "", 8)

    cons_cur = p6.get("water_consumed_cur", total_withdraw_cur) or 0
    cons_prev = p6.get("water_consumed_prev", 0) or 0
    pdf.table_row(["Total Water Consumed",
                   f"{cons_cur:.1f}", f"{cons_prev:.1f}"], widths)

    w_intensity = p6.get("water_intensity", 0) or 0
    if w_intensity:
        pdf.table_row(["Water Intensity (kL per Rs. turnover)",
                       f"{w_intensity:.8f}", "-"], widths, shaded=True)

    if p6.get("water_estimated"):
        pdf.ln(1)
        pdf.info_label(
            "Note: Water usage estimated using workers x 40L/day x working days "
            "(standard MSME benchmark)."
        )

    pdf.ln(2)
    pdf.sub_heading("4. Zero Liquid Discharge (Essential Q4)")
    pdf.kv_row("ZLD Implemented?", p6.get("zld", "No"), shaded=True)
    if p6.get("zld_desc"):
        pdf.kv_row("ZLD Coverage", p6.get("zld_desc", "-"))

    # ── Q5 & Q6: Emissions ────────────────────────────────────────────────
    pdf.add_page()
    pdf.sub_heading("5. Air Emissions (Essential Q5)")
    if p6.get("dna_air"):
        pdf.info_label(
            "Data Not Available - most MSMEs don't formally measure air pollutants. "
            "Third-party environmental consultant can measure NOx/SOx/PM for "
            "Rs. 5,000-15,000."
        )
    else:
        air_data = p6.get("air_data", {})
        cols = ["Pollutant", "Current FY", "Unit"]
        widths = [90, 50, 42]
        pdf.table_header(cols, widths)
        for i, ap in enumerate(["NOx", "SOx", "Particulate Matter (PM)",
                                 "VOC", "HAP"]):
            val = air_data.get(f"{ap}_cur", 0) or 0
            pdf.table_row([ap, f"{val}", "mg/m3"],
                          widths, shaded=(i % 2 == 0))
    pdf.ln(2)

    pdf.sub_heading("6. GHG Emissions - Scope 1 & 2 (Essential Q6)")
    cols = ["Parameter", "Current FY", "Unit"]
    widths = [110, 30, 42]
    pdf.table_header(cols, widths)

    scope1 = p6.get("scope1_co2", 0) or 0
    scope2 = p6.get("scope2_co2", 0) or 0
    scope12 = p6.get("scope12_co2", round(scope1 + scope2, 4))
    em_int = p6.get("emission_intensity", 0) or 0

    rows = [
        ("Total Scope 1 Emissions (Direct - from fuel)",
         f"{scope1:.3f}", "tCO2e"),
        ("Total Scope 2 Emissions (Indirect - from grid)",
         f"{scope2:.3f}", "tCO2e"),
        ("Total Scope 1 + 2",
         f"{scope12:.3f}", "tCO2e"),
        ("Scope 1+2 Intensity (per Rs. turnover)",
         f"{em_int:.10f}" if em_int else "-", "tCO2e/Rs."),
    ]
    for i, row in enumerate(rows):
        pdf.table_row(list(row), widths, shaded=(i % 2 == 0))
    pdf.ln(2)

    pdf.sub_heading("7. GHG Reduction Projects (Essential Q7)")
    pdf.paragraph(p6.get("ghg_reduction_projects", "None reported.") or "None reported.")

    # ── Q8: Waste ─────────────────────────────────────────────────────────
    pdf.add_page()
    pdf.sub_heading("8. Waste Generation (Essential Q8)")
    cols = ["Waste Category", "Current FY (MT)", "Previous FY (MT)"]
    widths = [100, 42, 40]
    pdf.table_header(cols, widths)

    waste_full = p6.get("waste_full", {})
    waste_cats = [
        ("Plastic Waste (A)", "plastic"),
        ("E-waste (B)", "ewaste"),
        ("Bio-medical Waste (C)", "biomedical"),
        ("Construction & Demolition (D)", "cd_waste"),
        ("Battery Waste (E)", "battery"),
        ("Other Hazardous Waste (G)", "hazardous"),
        ("Other Non-hazardous Waste (H)", "non_haz"),
    ]
    total_waste_cur = 0
    for i, (label, key) in enumerate(waste_cats):
        cur = waste_full.get(f"{key}_cur", 0) or 0
        prev = waste_full.get(f"{key}_prev", 0) or 0
        total_waste_cur += cur
        pdf.table_row([label, f"{cur:.3f}", f"{prev:.3f}"],
                      widths, shaded=(i % 2 == 0))

    pdf.set_font("Helvetica", "B", 8)
    pdf.set_fill_color(230, 245, 230)
    pdf.cell(100, 6, " Total Waste Generated", border=1, fill=True)
    pdf.cell(42, 6, f" {total_waste_cur:.3f}", border=1, fill=True)
    pdf.cell(40, 6, " -", border=1, fill=True)
    pdf.ln()
    pdf.set_font("Helvetica", "", 8)
    pdf.ln(2)

    # Recovery / Disposal
    pdf.sub_heading("Waste Recovery (Recycled / Reused)")
    recycled = p6.get("waste_recycled", 0) or 0
    reused = p6.get("waste_reused", 0) or 0
    other_rec = p6.get("waste_other_recovery", 0) or 0
    pdf.kv_row("Recycled (MT)", f"{recycled:.3f}", shaded=True)
    pdf.kv_row("Re-used (MT)", f"{reused:.3f}")
    pdf.kv_row("Other Recovery (MT)", f"{other_rec:.3f}", shaded=True)

    total_recovered = recycled + reused + other_rec
    if total_waste_cur > 0:
        recovery_pct = pct(total_recovered, total_waste_cur)
        pdf.kv_row("Total Recovery %", f"{recovery_pct}%")

    pdf.ln(2)
    pdf.sub_heading("Waste Disposal Methods")
    pdf.kv_row("Incinerated (MT)",
               f"{p6.get('waste_incinerated', 0):.3f}", shaded=True)
    pdf.kv_row("Landfilled (MT)",
               f"{p6.get('waste_landfilled', 0):.3f}")
    pdf.kv_row("Other Disposal (MT)",
               f"{p6.get('waste_other_disp', 0):.3f}", shaded=True)

    # ── Q9: Waste Management Practices ────────────────────────────────────
    pdf.ln(2)
    pdf.sub_heading("9. Waste Management Practices (Essential Q9)")
    pdf.paragraph(p6.get("waste_practices",
                          "Not yet documented.") or "Not yet documented.")

    # ── Q10-Q12: Compliance ───────────────────────────────────────────────
    pdf.add_page()
    pdf.sub_heading("10. Ecologically Sensitive Areas (Essential Q10)")
    near_sens = p6.get("near_sensitive") or p6.get("near_sensitive_area", "No")
    pdf.kv_row("Operations near ecologically sensitive areas?",
               near_sens, shaded=True)
    if p6.get("sensitive_details") or p6.get("sensitive_area_desc"):
        pdf.kv_row("Location & Compliance Status",
                   p6.get("sensitive_details") or
                   p6.get("sensitive_area_desc", "-"))
    pdf.ln(2)

    pdf.sub_heading("11. Environmental Impact Assessment (Essential Q11)")
    pdf.kv_row("EIA Conducted this FY?",
               p6.get("eia_done", "No"), shaded=True)
    if p6.get("eia_done") == "Yes":
        pdf.kv_row("Project Name", p6.get("eia_project", "-"))
        pdf.kv_row("EIA Notification No.",
                   p6.get("eia_notification", "-"), shaded=True)
        pdf.kv_row("External Agency?", p6.get("eia_external", "-"))
    pdf.ln(2)

    pdf.sub_heading("12. Environmental Law Compliance (Essential Q12)")
    pdf.kv_row("PCB Certificate (Consent to Operate)?",
               p6.get("pcb_compliant", "-"), shaded=True)
    if p6.get("pcb_expiry"):
        pdf.kv_row("PCB Certificate Expiry", p6.get("pcb_expiry", "-"))

    pdf.kv_row("Compliant with Water Act, Air Act, EP Act?",
               p6.get("env_compliant", "-"), shaded=True)

    if str(p6.get("env_compliant", "")).startswith("No"):
        details = (p6.get("env_noncompliance_desc") or
                   p6.get("noncompliance_details", "-"))
        if details and details != "-":
            pdf.kv_row("Non-Compliance Details", details)

    # ── Leadership Indicators ─────────────────────────────────────────────
    if (p6.get("renewable_kwh") or p6.get("water_discharge_kl") or
            p6.get("initiatives") or p6.get("disaster_plan") not in [None, "No"]):
        pdf.add_page()
        pdf.sub_heading("LEADERSHIP INDICATORS (Voluntary)")

        # L1: Renewable Energy
        ren = p6.get("renewable_kwh", 0) or 0
        nonren = p6.get("nonrenewable_kwh", 0) or 0
        if ren > 0 or nonren > 0:
            pdf.sub_heading("L1. Renewable vs Non-Renewable Energy")
            total_e = ren + nonren
            cols = ["Source", "kWh/year", "% of Total"]
            widths = [90, 50, 42]
            pdf.table_header(cols, widths)
            ren_pct = pct(ren, total_e) if total_e > 0 else 0
            nonren_pct = pct(nonren, total_e) if total_e > 0 else 0
            pdf.table_row(["From Renewable Sources (Solar/Wind/Biogas)",
                           f"{ren:,.0f}", f"{ren_pct}%"],
                          widths, shaded=True)
            pdf.table_row(["From Non-Renewable Sources (Grid/Diesel)",
                           f"{nonren:,.0f}", f"{nonren_pct}%"], widths)
            pdf.ln(2)

        # L2: Water Discharge
        if p6.get("water_discharge_kl", 0) > 0:
            pdf.sub_heading("L2. Water Discharge")
            pdf.kv_row("Total Water Discharged (kL/year)",
                       f"{p6.get('water_discharge_kl', 0):.1f}", shaded=True)
            pdf.kv_row("Level of Treatment",
                       p6.get("water_discharge_treated", "-"))
            pdf.ln(2)

        # L3: Water Stress
        if p6.get("water_stress_area") == "Yes":
            pdf.sub_heading("L3. Operations in Water-Stressed Areas")
            pdf.kv_row("Water-stressed area?", "Yes", shaded=True)
            if p6.get("water_stress_desc"):
                pdf.kv_row("Details", p6.get("water_stress_desc"))
            pdf.ln(2)

        # L4: Scope 3
        if not p6.get("dna_scope3") and p6.get("scope3_co2", 0) > 0:
            pdf.sub_heading("L4. Scope 3 Emissions")
            pdf.kv_row("Scope 3 Emissions (tCO2e)",
                       f"{p6.get('scope3_co2', 0):.3f}", shaded=True)
            pdf.ln(2)

        # L6: Resource Efficiency Initiatives
        if p6.get("initiatives"):
            pdf.sub_heading("L6. Resource Efficiency Initiatives")
            pdf.paragraph(p6.get("initiatives", "-"))
            pdf.ln(2)

        # Green Initiatives (Quick Mode)
        green_preset = p6.get("green_preset", [])
        green_other = p6.get("green_efforts", "")
        if green_preset or green_other:
            pdf.sub_heading("Green Initiatives Documented")
            if green_preset:
                pdf.paragraph("- " + "\n- ".join(green_preset))
            if green_other and str(green_other).strip():
                pdf.paragraph(green_other)
            pdf.ln(2)

        # L7: Disaster Plan
        if p6.get("disaster_plan") and p6.get("disaster_plan") != "No":
            pdf.sub_heading("L7. Business Continuity & Disaster Plan")
            pdf.kv_row("Plan Status?", p6.get("disaster_plan", "-"), shaded=True)
            if p6.get("disaster_desc"):
                pdf.paragraph(p6.get("disaster_desc", "-"))
            pdf.ln(2)

        # L9: Value Chain Environmental Assessment
        vc_pct = p6.get("vc_env_pct", 0) or 0
        if vc_pct > 0:
            pdf.sub_heading("L9. Value Chain Environmental Assessment")
            pdf.kv_row("% of value chain partners assessed",
                       f"{vc_pct}%", shaded=True)
            if p6.get("vc_env_actions"):
                pdf.kv_row("Corrective Actions", p6.get("vc_env_actions", "-"))

    # Score
    score = p6.get("score", 0)
    if score:
        pdf.ln(3)
        pdf.sub_heading("Principle 6 Score")
        pdf.kv_row("Environmental Score", f"{score}/100", shaded=True)


# ─────────────────────────────────────────────────────────────────────────────
# PRINCIPLES 7, 8, 9 (Full BRSR format)
# ─────────────────────────────────────────────────────────────────────────────
def render_p789(pdf, data):
    p789 = data.get("p789", {})
    if not p789:
        return

    # ═════════════════════════════════════════════════════════════════════
    # PRINCIPLE 7
    # ═════════════════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.principle_heading("PRINCIPLE 7",
                           "Policy Advocacy (Responsible Engagement)")

    pdf.sub_heading("1. Trade & Industry Associations (Essential Q1)")
    pdf.kv_row("Member of any business association?",
               p789.get("is_association_member", "No"), shaded=True)

    # Quick mode stores 'associations_text' and 'associations_list'
    # Full mode stores in 'p7_assoc_full' dict
    p7_assoc_full = p789.get("p7_assoc_full", {})
    has_full = any(p7_assoc_full.get(f"name_{i}", "") for i in range(1, 11))

    if has_full:
        pdf.ln(1)
        cols = ["S.No.", "Association Name", "Reach"]
        widths = [18, 125, 39]
        pdf.table_header(cols, widths)
        idx = 1
        for i in range(1, 11):
            name = p7_assoc_full.get(f"name_{i}", "")
            reach = p7_assoc_full.get(f"reach_{i}", "-")
            if name:
                pdf.table_row([str(idx), name, reach],
                              widths, shaded=(idx % 2 == 0))
                idx += 1
    elif p789.get("associations_list"):
        pdf.ln(1)
        cols = ["S.No.", "Association Name"]
        widths = [18, 164]
        pdf.table_header(cols, widths)
        for i, name in enumerate(p789.get("associations_list", []), 1):
            pdf.table_row([str(i), name], widths, shaded=(i % 2 == 0))
    elif p789.get("associations_text"):
        pdf.kv_row("Associations", p789.get("associations_text"))

    pdf.ln(2)

    # Anti-competitive
    pdf.sub_heading("2. Anti-Competitive Conduct (Essential Q2)")
    pdf.kv_row("Any adverse orders?",
               p789.get("anti_competitive", "No"), shaded=True)

    p7_ac_cases = p789.get("p7_ac_cases", {})
    has_cases = any(p7_ac_cases.get(f"auth_{i}", "") for i in range(1, 4))
    if has_cases:
        pdf.ln(1)
        cols = ["Authority", "Brief of Case", "Corrective Action"]
        widths = [50, 66, 66]
        pdf.table_header(cols, widths)
        for i in range(1, 4):
            auth = p7_ac_cases.get(f"auth_{i}", "")
            if auth:
                brief = (p7_ac_cases.get(f"brief_{i}", "-") or "-")[:55]
                action = (p7_ac_cases.get(f"action_{i}", "-") or "-")[:55]
                pdf.table_row([auth, brief, action],
                              widths, shaded=(i % 2 == 0))
    elif p789.get("anti_competitive_details"):
        pdf.paragraph(p789.get("anti_competitive_details", "-"))

    pdf.ln(2)

    # Leadership: Policy Advocacy
    pdf.sub_heading("L1. Public Policy Positions Advocated (Leadership)")
    p7_pol = p789.get("p7_pol_advocacy", {})
    has_pol = any(p7_pol.get(f"policy_{i}", "") for i in range(1, 4))
    if has_pol:
        cols = ["Policy Advocated", "Method", "Public?", "Web Link"]
        widths = [60, 48, 25, 49]
        pdf.table_header(cols, widths)
        for i in range(1, 4):
            pol = p7_pol.get(f"policy_{i}", "")
            if pol:
                pdf.table_row([
                    pol[:40],
                    (p7_pol.get(f"method_{i}", "-") or "-")[:30],
                    p7_pol.get(f"public_{i}", "-"),
                    (p7_pol.get(f"link_{i}", "-") or "-")[:32]
                ], widths, shaded=(i % 2 == 0))
    elif p789.get("policy_advocacy") == "Yes":
        pdf.kv_row("Policy Advocacy Active?", "Yes", shaded=True)
        if p789.get("policy_advocacy_examples"):
            pdf.paragraph(p789.get("policy_advocacy_examples", "-"))
    else:
        pdf.info_label(
            "Most MSMEs do not engage in public policy advocacy - "
            "marked as Not Applicable."
        )

    # ═════════════════════════════════════════════════════════════════════
    # PRINCIPLE 8
    # ═════════════════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.principle_heading("PRINCIPLE 8", "Inclusive Growth & Community")

    # Q1: SIA
    pdf.sub_heading("1. Social Impact Assessments (Essential Q1)")
    sia_app = p789.get("sia_applicable", "Not Applicable")
    pdf.kv_row("SIA Applicable?", sia_app, shaded=True)

    # Q2: R&R
    pdf.sub_heading("2. Rehabilitation & Resettlement (Essential Q2)")
    rr_app = p789.get("rr_applicable", "Not Applicable")
    pdf.kv_row("R&R Applicable?", rr_app, shaded=True)

    # Q3: Community Grievance
    pdf.sub_heading("3. Community Grievance Mechanism (Essential Q3)")
    mech_desc = (p789.get("community_grievance_desc") or
                 p789.get("community_grievance", "-"))
    pdf.paragraph(mech_desc)

    # Q4: Local Sourcing
    pdf.sub_heading("4. Local & MSME Sourcing (Essential Q4)")
    cols = ["Source Type", "Current FY (%)", "Previous FY (%)"]
    widths = [100, 45, 37]
    pdf.table_header(cols, widths)

    msme_cur = p789.get("src_msme_cur", p789.get("local_sourcing_pct", 0)) or 0
    msme_prev = p789.get("src_msme_prev", 0) or 0
    dist_cur = p789.get("src_district_cur", 0) or 0
    dist_prev = p789.get("src_district_prev", 0) or 0
    pdf.table_row([
        "Directly from MSMEs / small producers",
        f"{msme_cur}%", f"{msme_prev}%"
    ], widths, shaded=True)
    pdf.table_row([
        "From within district / neighbouring districts",
        f"{dist_cur}%", f"{dist_prev}%"
    ], widths)

    pdf.ln(2)

    # Local hiring & community support (from Quick mode)
    pdf.sub_heading("Additional MSME Inclusive Growth Metrics")
    pdf.kv_row("Local Hiring %",
               f"{p789.get('local_hiring_pct', 0)}%", shaded=True)
    pdf.kv_row("Community Support Type",
               p789.get("community_support", "-"))
    if p789.get("community_support_details"):
        pdf.paragraph(p789.get("community_support_details", "-"))

    # ── Leadership P8 ─────────────────────────────────────────────────────
    pdf.add_page()
    pdf.sub_heading("LEADERSHIP INDICATORS - P8")

    # L3: Preferential Procurement
    pdf.sub_heading("L3. Preferential Procurement (Vulnerable Groups)")
    pdf.kv_row("Preference to vulnerable group suppliers?",
               p789.get("pref_vulnerable_proc", "No"), shaded=True)
    if p789.get("pref_vulnerable_proc") == "Yes":
        groups = p789.get("pref_groups") or p789.get("pref_vulnerable_details", "-")
        pdf.kv_row("Groups Procured From", groups)
        pct_val = p789.get("pref_pct", 0)
        if pct_val:
            pdf.kv_row("% of Total Procurement",
                       f"{pct_val}%", shaded=True)

    pdf.ln(2)

    # L2: Aspirational Districts CSR
    pdf.sub_heading("L2. CSR in Aspirational Districts")
    asp_app = p789.get("asp_applicable", "Not Applicable")
    pdf.kv_row("CSR in Aspirational Districts?", asp_app, shaded=True)

    pdf.ln(2)

    # L4+L5: Traditional Knowledge IP
    pdf.sub_heading("L4-L5. Traditional Knowledge-Based IP")
    ip_app = p789.get("ip_trad_applicable", "Not Applicable")
    pdf.kv_row("IP based on Traditional Knowledge?", ip_app, shaded=True)

    pdf.ln(2)

    # L6: CSR Beneficiaries
    if p789.get("csr_benef"):
        pdf.sub_heading("L6. CSR Beneficiaries")
        pdf.paragraph(p789.get("csr_benef", "-"))

    # Grievance mechanism used by community (Quick mode)
    if p789.get("community_grievance"):
        pdf.sub_heading("Community Grievance Mechanism Used")
        pdf.kv_row("Mechanism",
                   p789.get("community_grievance", "-"), shaded=True)

    # ═════════════════════════════════════════════════════════════════════
    # PRINCIPLE 9
    # ═════════════════════════════════════════════════════════════════════
    pdf.add_page()
    pdf.principle_heading("PRINCIPLE 9", "Customer Responsibility")

    # Q1: Complaint Mechanism
    pdf.sub_heading("1. Customer Complaint Mechanism (Essential Q1)")
    mech_p9 = p789.get("p9_mechanism_desc", "")
    if mech_p9:
        pdf.paragraph(mech_p9)
    else:
        channels = p789.get("customer_channels", [])
        pdf.kv_row("Complaint Channels Available",
                   ", ".join(channels) if channels else "-", shaded=True)
        pdf.kv_row("Complaint Tracking Method",
                   p789.get("complaint_record", "-"))

    pdf.ln(2)

    # Q2: Product Information Coverage
    pdf.sub_heading("2. Product Information Coverage (Essential Q2)")
    info_pct = p789.get("p9_info_pct", {})
    cols = ["Information Type", "% of Turnover"]
    widths = [140, 42]
    pdf.table_header(cols, widths)
    info_rows = [
        ("Environmental and social parameters",
         f"{info_pct.get('env_soc', 0)}%"),
        ("Safe and responsible usage",
         f"{info_pct.get('safe_usage', 0)}%"),
        ("Recycling / safe disposal",
         f"{info_pct.get('recycling', 0)}%"),
    ]
    for i, row in enumerate(info_rows):
        pdf.table_row(list(row), widths, shaded=(i % 2 == 0))

    if p789.get("product_info_details"):
        pdf.ln(1)
        pdf.info_label(f"How info is provided: "
                       f"{p789.get('product_info_details', '-')}")

    pdf.ln(2)

    # Q3: Complaints by Category (BIG TABLE)
    pdf.add_page()
    pdf.sub_heading("3. Customer Complaints by Category (Essential Q3)")
    cols = ["Category", "Cur: Rec", "Cur: Pen", "Prev: Rec", "Prev: Pen"]
    widths = [62, 30, 30, 30, 30]
    pdf.table_header(cols, widths)

    cd = p789.get("p9_complaint_data", {})
    total_cur_rec = 0
    total_cur_pen = 0
    cats_p9 = ["Data privacy", "Advertising", "Cyber-security",
               "Delivery of essential services",
               "Restrictive Trade Practices",
               "Unfair Trade Practices", "Other"]
    for i, cat in enumerate(cats_p9):
        cr = cd.get(f"{cat}_cur_rec", 0) or 0
        cp = cd.get(f"{cat}_cur_pen", 0) or 0
        pr = cd.get(f"{cat}_prev_rec", 0) or 0
        pp = cd.get(f"{cat}_prev_pen", 0) or 0
        total_cur_rec += cr
        total_cur_pen += cp
        pdf.table_row([cat, str(cr), str(cp), str(pr), str(pp)],
                      widths, shaded=(i % 2 == 0))

    # If full-mode data is empty but Quick Mode data exists, show that
    if total_cur_rec == 0 and p789.get("complaints_received_yr", 0) > 0:
        pdf.ln(1)
        pdf.info_label("Quick Mode totals (category breakdown pending):")
        pdf.kv_row("Total Complaints Received",
                   p789.get("complaints_received_yr", 0), shaded=True)
        pdf.kv_row("Total Complaints Resolved",
                   p789.get("complaints_resolved_yr", 0))
        res_pct = pct(p789.get("complaints_resolved_yr", 0),
                      p789.get("complaints_received_yr", 0))
        pdf.kv_row("Resolution Rate", f"{res_pct}%", shaded=True)

    pdf.ln(2)

    # Q4: Product Recalls
    pdf.sub_heading("4. Product Recalls (Essential Q4)")
    pdf.kv_row("Any recalls in last 3 years?",
               p789.get("product_recalls", "No"), shaded=True)

    if (p789.get("vol_recalls_num", 0) > 0 or
            p789.get("forced_recalls_num", 0) > 0):
        cols = ["Type", "Number", "Reasons"]
        widths = [40, 30, 112]
        pdf.table_header(cols, widths)
        pdf.table_row(["Voluntary",
                       str(p789.get("vol_recalls_num", 0)),
                       (p789.get("vol_recalls_reason", "-") or "-")[:90]],
                      widths, shaded=True)
        pdf.table_row(["Forced",
                       str(p789.get("forced_recalls_num", 0)),
                       (p789.get("forced_recalls_reason", "-") or "-")[:90]],
                      widths)
    elif p789.get("product_recalls_details"):
        pdf.paragraph(p789.get("product_recalls_details", "-"))

    pdf.ln(2)

    # Q5: Cybersecurity & Data Privacy Policy
    pdf.sub_heading("5. Cybersecurity & Data Privacy Policy (Essential Q5)")
    cyber = p789.get("cyber_policy", "No")
    pdf.kv_row("Formal Policy in Place?", cyber, shaded=True)
    if p789.get("cyber_link"):
        pdf.kv_row("Web Link", p789.get("cyber_link", "-"))

    pdf.kv_row("Stores Customer Data?",
               p789.get("stores_customer_data", "No"), shaded=True)
    pdf.kv_row("Basic Data Privacy Rule in Place?",
               p789.get("data_privacy_rule", "-"))

    pdf.ln(2)

    # Q6: Corrective Actions
    if p789.get("p9_corrective"):
        pdf.sub_heading("6. Corrective Actions (Essential Q6)")
        pdf.paragraph(p789.get("p9_corrective", "-"))

    # ── P9 Leadership ─────────────────────────────────────────────────────
    if (p789.get("info_channels") or p789.get("safe_usage_education") or
            p789.get("data_breaches_num", 0) > 0):
        pdf.add_page()
        pdf.sub_heading("LEADERSHIP INDICATORS - P9")

        if p789.get("info_channels"):
            pdf.sub_heading("L1. Product Information Channels")
            pdf.paragraph(p789.get("info_channels", "-"))
            pdf.ln(1)

        if p789.get("safe_usage_education"):
            pdf.sub_heading("L2. Safe Usage Education")
            pdf.paragraph(p789.get("safe_usage_education", "-"))
            pdf.ln(1)

        if p789.get("service_disruption"):
            pdf.sub_heading("L3. Service Disruption Communication")
            pdf.paragraph(p789.get("service_disruption", "-"))
            pdf.ln(1)

        pdf.sub_heading("L4. Product Info Beyond Legal + Customer Surveys")
        pdf.kv_row("Info beyond legal requirements?",
                   p789.get("extra_info_display", "-"), shaded=True)
        pdf.kv_row("Customer satisfaction surveys?",
                   p789.get("surveys_done", "-"))
        pdf.ln(1)

        # L5: Data Breaches
        breaches = p789.get("data_breaches_num", 0) or 0
        if breaches > 0:
            pdf.sub_heading("L5. Data Breaches")
            pdf.kv_row("Number of Data Breaches", breaches, shaded=True)
            pdf.kv_row("% Involving Personal Information",
                       f"{p789.get('data_breaches_pii_pct', 0)}%")

    # Combined Score
    score = p789.get("score", 0)
    if score:
        pdf.ln(3)
        pdf.sub_heading("Combined P7 + P8 + P9 Score")
        pdf.kv_row("Policy, Community & Customer Score",
                   f"{score}/100", shaded=True)


# ─────────────────────────────────────────────────────────────────────────────
# OVERALL RECOMMENDATIONS SUMMARY
# ─────────────────────────────────────────────────────────────────────────────
def render_recommendations(pdf, data):
    pdf.add_page()
    pdf.section_heading("RECOMMENDATIONS & NEXT STEPS")

    recs = []

    # Section A based
    if data.get("board_female", 0) == 0 and data.get("board_total", 0) > 0:
        recs.append("Add at least one woman to your Board of Directors.")
    if not data.get("has_grievance"):
        recs.append("Set up a formal grievance mechanism "
                    "(dedicated email or register).")

    # Section B based
    b = data.get("section_b", {})
    missing_policies = [code for code in PRINCIPLE_NAMES
                        if b.get(f"{code}_policy") != "Yes"]
    if len(missing_policies) >= 5:
        recs.append(f"{len(missing_policies)} of 9 NGRBC policies not yet in place. "
                    "Use the built-in policy generator to create simple starter policies.")

    # P1
    p1 = data.get("p1", {}) or data.get("c_p1", {})
    if p1 and p1.get("training_conducted") != "Yes":
        recs.append("Conduct basic ethics / anti-bribery training for your team. "
                    "Even a 1-hour session with attendance record counts.")

    # P2
    p2 = data.get("p2", {}) or data.get("c_p2", {})
    if p2 and p2.get("sustainable_sourcing") != "Yes":
        recs.append("Document sustainable sourcing practices - even informal ones. "
                    "Large buyers increasingly check this.")

    # P3
    p3 = data.get("p3", {}) or data.get("c_p3", {})
    if p3 and p3.get("safety_training") != "Yes":
        recs.append("Conduct workplace safety training. "
                    "Even fire-drill + first-aid briefing counts.")

    # P4+5
    p45 = data.get("p4_5", {}) or data.get("c_p45", {})
    if p45 and p45.get("posh_committee") != "Yes":
        recs.append("Form a POSH committee (Prevention of Sexual Harassment). "
                    "Mandatory under Indian law for any workplace with 10+ employees.")

    # P6
    p6 = data.get("p6", {})
    if p6:
        if not str(p6.get("pcb_compliant", "")).startswith("Yes"):
            recs.append("Obtain PCB Consent to Operate (CTO) from your state "
                        "Pollution Control Board - highest priority.")

    # P789
    p789 = data.get("p789", {})
    if p789:
        if p789.get("complaint_record") == "No record":
            recs.append("Start a simple customer complaint register. "
                        "Even a notebook with Date | Name | Issue | Action works.")

    if not recs:
        recs.append("Your BRSR disclosure is comprehensive. Focus on annual "
                    "improvement and year-over-year comparison.")

    for i, rec in enumerate(recs, 1):
        pdf.recommendation(f"{i}. {rec}")
        pdf.ln(0.5)


# ─────────────────────────────────────────────────────────────────────────────
# COVER PAGE
# ─────────────────────────────────────────────────────────────────────────────
def render_cover(pdf, d, overall_score):
    """Dedicated cover page — no top bar, professional layout."""

    # ── Top accent strip (subtle dark green) ──────────────────────────
    pdf.set_fill_color(15, 76, 44)
    pdf.rect(0, 0, 210, 4, 'F')

    pdf.ln(14)

    # ── Ecosetu logo (centered) ───────────────────────────────────────
    try:
        pdf.image(ECOSETU_LOGO, x=80, y=pdf.get_y(), w=50)
        pdf.ln(20)
    except Exception:
        pass  # If logo missing, skip gracefully

    # ── Small report category label ───────────────────────────────────
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(99, 102, 241)
    pdf.cell(0, 5, "BRSR COMPLIANCE REPORT", align="C", ln=True)
    pdf.ln(3)
    # ── Main title ────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 24)
    pdf.set_text_color(15, 23, 42)
    company = clean(d.get("company_name", "Your Company"))
    pdf.cell(0, 12, company, align="C", ln=True)

    # ── Subtitle: full BRSR name ─────────────────────────────────────
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(0, 6,
             "Business Responsibility & Sustainability Report",
             align="C", ln=True)
    pdf.ln(4)

    # ── Decorative divider (short indigo line) ────────────────────────
    pdf.set_draw_color(99, 102, 241)
    pdf.set_line_width(1.2)
    pdf.line(85, pdf.get_y(), 125, pdf.get_y())
    pdf.set_line_width(0.2)
    pdf.ln(8)

    # ── Three info cards row (FY | Class | Type) ──────────────────────
    fy = clean(d.get("financial_year", "-"))
    msme = clean(get_msme_class(d.get("turnover_lakhs", 0)))
    btype = clean(d.get("business_type_tier", d.get("ownership", "-")))

    card_w = 58
    gap = 4
    start_x = (210 - (3 * card_w + 2 * gap)) / 2
    y = pdf.get_y()

    info_cards = [
        ("FINANCIAL YEAR", fy),
        ("ENTERPRISE CLASS", msme),
        ("BUSINESS TYPE", btype),
    ]

    for i, (lbl, val) in enumerate(info_cards):
        x = start_x + i * (card_w + gap)
        # Card background
        pdf.set_fill_color(248, 250, 252)
        pdf.set_draw_color(226, 232, 240)
        pdf.rect(x, y, card_w, 18, 'FD')
        # Label
        pdf.set_xy(x, y + 3)
        pdf.set_font("Helvetica", "B", 7)
        pdf.set_text_color(99, 102, 241)
        pdf.cell(card_w, 4, lbl, align="C")
        # Value
        pdf.set_xy(x, y + 9)
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(card_w, 6, val[:22], align="C")

    pdf.set_y(y + 22)
    pdf.ln(8)

    # ── Big score circle/box ──────────────────────────────────────────
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(0, 5, "OVERALL BRSR READINESS SCORE", align="C", ln=True)
    pdf.ln(2)

    # Color based on score
    if overall_score >= 70:
        score_color = (16, 185, 129)  # emerald
        rating = "Strong - Bank-ready posture"
    elif overall_score >= 40:
        score_color = (245, 158, 11)  # amber
        rating = "Developing - Room to improve"
    else:
        score_color = (239, 68, 68)  # red
        rating = "Early stage - Action needed"

    # Score number — huge
    pdf.set_font("Helvetica", "B", 48)
    pdf.set_text_color(*score_color)
    pdf.cell(0, 18, f"{overall_score}", align="C", ln=True)

    # "/100"
    pdf.set_font("Helvetica", "", 12)
    pdf.set_text_color(148, 163, 184)
    pdf.cell(0, 5, "/ 100", align="C", ln=True)
    pdf.ln(4)

    # Rating tag
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*score_color)
    pdf.cell(0, 5, rating, align="C", ln=True)
    pdf.ln(8)

    # ── Section-wise scores table ─────────────────────────────────────
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(0, 6, "Section-wise Scores", align="C", ln=True)
    pdf.ln(2)

    # Center the table
    cols = ["Section", "Score"]
    widths = [110, 35]
    table_x = (210 - sum(widths)) / 2
    pdf.set_x(table_x)

    # Custom table header
    pdf.set_fill_color(238, 242, 255)
    pdf.set_text_color(67, 56, 202)
    pdf.set_font("Helvetica", "B", 8)
    pdf.cell(widths[0], 7, " Section", border=0, fill=True)
    pdf.cell(widths[1], 7, " Score", border=0, fill=True, ln=True)

    # Build score list
    scores_list = [("Section A — General Disclosures", overall_score)]
    b = d.get("section_b", {})
    if b:
        scores_list.append(
            ("Section B — Management & Policies",
             b.get("score") if b.get("score") else "Filled"))

    for key, label in [
        ("p1", "P1 — Ethics"),
        ("p2", "P2 — Sustainable Products"),
        ("p3", "P3 — Employee Wellbeing"),
        ("p4_5", "P4+P5 — Stakeholders & Human Rights"),
        ("p6", "P6 — Environment"),
        ("p789", "P7+P8+P9 — Policy, Community, Customers"),
    ]:
        pdata = d.get(key) or {}
        score = pdata.get("score") if pdata else None
        if score is not None and score != 0:
            scores_list.append((label, f"{score}/100"))
        elif pdata:
            scores_list.append((label, "Filled"))

    # Render rows
    pdf.set_text_color(51, 65, 85)
    pdf.set_font("Helvetica", "", 8.5)
    for i, (lbl, val) in enumerate(scores_list):
        pdf.set_x(table_x)
        if i % 2 == 0:
            pdf.set_fill_color(255, 255, 255)
        else:
            pdf.set_fill_color(248, 250, 252)
        pdf.cell(widths[0], 6, f" {clean(lbl)}", border=0, fill=True)
        pdf.set_font("Helvetica", "B", 8.5)
        pdf.cell(widths[1], 6, f" {clean(str(val))}", border=0, fill=True, ln=True)
        pdf.set_font("Helvetica", "", 8.5)

    # ── Footer of cover ───────────────────────────────────────────────
    pdf.set_y(-32)
    pdf.set_draw_color(226, 232, 240)
    pdf.line(20, pdf.get_y(), 190, pdf.get_y())
    pdf.ln(3)

    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(100, 116, 139)
    pdf.cell(0, 4,
             f"Generated on {datetime.now().strftime('%d %B %Y')}",
             align="C", ln=True)
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(15, 76, 44)
    pdf.cell(0, 4,
             "Ecosetu  -  An initiative by Keprin Overseas Corporation, Bhavnagar",
             align="C", ln=True)
    pdf.set_font("Helvetica", "I", 7.5)
    pdf.set_text_color(148, 163, 184)
    pdf.cell(0, 4,
             "Built by Meet Ketankumar Vaghani, Certified ESG Professional",
             align="C", ln=True)

# ─────────────────────────────────────────────────────────────────────────────
# MAIN ENTRY POINT
# ─────────────────────────────────────────────────────────────────────────────
def generate_brsr_pdf(data, esg_score):
    """
    data: merged dict with Section A keys at top level,
          and nested keys 'section_b', 'p1', 'p2', 'p3', 'p4_5', 'p6', 'p789'
    esg_score: int overall score (0-100)
    Returns: bytes of PDF
    """
    pdf = BRSRReport(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # Cover
    render_cover(pdf, data, esg_score)

    # Section A
    pdf.add_page()
    render_section_a(pdf, data)

    # Section B
    if data.get("section_b"):
        render_section_b(pdf, data)

    # Section C — Principles
    render_p1(pdf, data)
    render_p2(pdf, data)
    render_p3(pdf, data)
    render_p45(pdf, data)
    render_p6(pdf, data)
    render_p789(pdf, data)

    # Recommendations
    render_recommendations(pdf, data)

    # Disclaimer
    pdf.ln(6)
    pdf.set_font("Helvetica", "I", 7.5)
    pdf.set_text_color(130, 130, 130)
    pdf.multi_cell(0, 4,
        "Disclaimer: This report has been generated using the BRSR Tool for MSMEs "
        "based on data provided by the company. It is based on the SEBI BRSR format "
        "and simplified for MSME use. This tool does not constitute legal or "
        "regulatory advice. Companies are advised to consult a qualified CA or ESG "
        "consultant for final submission.",
        align="C"
    )

    return bytes(pdf.output())
